version: '2'
services:
    db:
        image: postgres:9.4
        container_name: db
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
    odoo:
        build: .
        container_name: odoo
        ports:
            - "127.0.0.1:8069:8069"
        links:
            - db:db
        depends_on:
            - db
        tty: true
        environment:
            - PGHOST=db
            - PGUSER=odoo
            - PGPASSWORD=odoo
        volumes:
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
